import { Main } from './styles'

import { Location } from './Location'
import { SignIn } from './SignIn'

import Head from 'next/head'

const Home = () => (
  <>
    <Head>
      <title>Home</title>

      <link rel='icon' href='/favicon.ico' />

      <meta name='description' content='Generated by create next app' />
    </Head>

    <Main>
      <SignIn />

      <Location />
    </Main>

    <section></section>
  </>
)

export default Home
