import { BackgroundImages, SignIn, SignInForm } from './styles'

import Head from 'next/head'

const Home = () => {
  return (
    <>
      <Head>
        <title>Home</title>

        <link rel='icon' href='/favicon.ico' />

        <meta name='description' content='Generated by create next app' />
      </Head>

      <SignIn>
        <BackgroundImages>bgImage</BackgroundImages>

        <SignInForm>logo</SignInForm>
      </SignIn>

      <section></section>
    </>
  )
}

export default Home
